name: build

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: delete symlink
        run: rm -fr demo/pkg

      - name: setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: install build wasm-pack
        uses: qmaru/wasm-pack-action@v0.5.0
        with:
          version: 'latest'

      - name: build wasm
        run: |
          bash ./scripts/build-notemine-wasm.sh 

      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '20'

      - name: install
        run: yarn install

      - name: webpack
        run: yarn build

      - name: uplooad artifact
        uses: actions/upload-artifact@v3
        with:
          name: notemine-build
          path: ./