name: test

on:
  push:
    branches: ["master"]
  workflow_dispatch:
  workflow_run:
    workflows:
      - build
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: notemine-build
          path: ./

      - name: vitest
        run: yarn test